//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int orderId { get; set; }
        public string email { get; set; }
        public string productname { get; set; }
        public decimal productprice { get; set; }
        public int productquantity { get; set; }
        public string status { get; set; }
    }
}
